package io.dsh.bridge;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Tiny built-in two-language table for the bridge UI (and its notification).
 *
 * The bridge has no RUN_COMMAND permission, so unlike the Console app it cannot ask Termux for the
 * value of ~/.dsh-lang. Instead:
 *   · its own choice is persisted in SharedPreferences, and
 *   · the Termux side can push the current language into it over the loopback socket
 *     (`droid-sock lang <zh|en|auto>` / `dsh-lang set …` does it for you), so the app, the page panel
 *     and the widgets end up on the same language.
 * A key that is missing returns the English string unchanged (degrades to one English line).
 */
final class Lang {
    static final String[] MODES = {"auto", "zh", "en"};
    private static final Map<String, String> ZH = new HashMap<>();
    private static String mode = "auto";
    private static String cur = "en";

    static {
        // >>> generated by tools/i18n-table — do not edit by hand >>>
        ZH.put("   (The volume-key gesture, the in-app red button and the Termux widget are unaffected)", "   （音量键手势、App 里的红色按钮、Termux 组件都不受影响）");
        ZH.put("   1. The red button below\n", "   1. 下面那个红色按钮\n");
        ZH.put("   2. Hold volume + and volume − together for 3 seconds\n", "   2. 音量＋ 和 音量－ 同时按住 3 秒\n");
        ZH.put("   3. Emergency stop inside the DSH Bridge is running notification\n", "   3. 「DSH 桥正在运行」通知里的紧急停止\n");
        ZH.put("   4. The Termux home-screen widget item 0_emergency-stop", "   4. Termux 桌面组件里的 0_emergency-stop");
        ZH.put("   Tap ③ Open this app's notification settings below to enable it.", "   点下面的 ③ 打开本应用的通知设置即可启用。");
        ZH.put("  (tap Copy token to copy it)", "  （点「复制 token」可取）");
        ZH.put("  v", "  v");
        ZH.put(" min", " 分钟");
        ZH.put(" min idle", " 分钟自动停止");
        ZH.put(" · checking for a newer release…", " · 正在检查有没有新版本…");
        ZH.put(" · could not check for updates now (no network?)", " · 现在查不了更新（没网？）");
        ZH.put(" · hold volume +/- for 3s to stop", " · 音量+/- 同时按住 3 秒紧急停止");
        ZH.put(" · local is newer than the repo (the repo only has v", " · 本地比仓库新（仓库只有 v");
        ZH.put(" · tap the project page to update", " · 点项目主页更新");
        ZH.put(" · up to date", " · 已是最新");
        ZH.put(" → the repo has ", " → 仓库最新 ");
        ZH.put("(Also: this app does not autostart; it will not come up by itself after a phone restart)", "（另外：本应用不自动启动；手机重启后它不会自己起来）");
        ZH.put("(new in v1.5: turns wireless debugging on automatically when online, used by widget 8)", "（v1.5 新增：联网时自动打开无线调试，组件 8 会用到）");
        ZH.put(")", "）");
        ZH.put("About this app", "关于本应用");
        ZH.put("Accessibility is unbound and the app exits. On this vivo it may not be wakeable again - you would have to open DSH Bridge by hand.", "会让 App 退出并解绑无障碍。这台 vivo 上可能再也唤不回来 —— 只能你手动打开「DSH 桥」。");
        ZH.put("Accessibility: ", "无障碍：");
        ZH.put("Auto-stop after ", "空闲 ");
        ZH.put("Bridge running", "桥运行中");
        ZH.put("Bridge state", "桥状态");
        ZH.put("Bridge: just dropped (wakeable)", "桥：刚断（可唤醒）");
        ZH.put("Bridge: running", "桥：运行中");
        ZH.put("Cancel", "取消");
        ZH.put("Cannot open notification settings: ", "打不开通知设置：");
        ZH.put("Channels (adb and bridge separate)", "通道（adb 与桥分开）");
        ZH.put("Copies the bridge token, which the Termux side needs. Handing it out is handing out the key to this channel.", "复制桥的 token（Termux 侧要用）。把它交出去等于交出这条通道的钥匙。");
        ZH.put("Copy token", "复制 token");
        ZH.put("DSH Bridge", "DSH 桥");
        ZH.put("DSH Bridge emergency-stopped: ", "DSH 桥已紧急停止：");
        ZH.put("DSH Bridge is no longer running", "DSH 桥已不在运行");
        ZH.put("DSH Bridge is running", "DSH 桥正在运行");
        ZH.put("DSH Bridge started: hold volume +/- together for 3s for emergency stop", "DSH 桥已启动：音量+/- 同时按住 3 秒可紧急停止");
        ZH.put("DSH Bridge stays stopped (you turned it off earlier); tap widgets 1/7/8 to resume", "DSH 桥保持停止（你之前关过它）；点组件 1/7/8 可恢复");
        ZH.put("DSH Bridge: ", "DSH 桥：");
        ZH.put("Danger zone · only you can undo it by hand", "危险操作 · 只能你手动恢复");
        ZH.put("Emergency", "紧急");
        ZH.put("Emergency stop", "紧急停止");
        ZH.put("Emergency stop done; the accessibility service is off", "已紧急停止，无障碍服务已关闭");
        ZH.put("English", "English");
        ZH.put("Failed to open settings: ", "打开设置失败：");
        ZH.put("For the first setup, or after the system unbound the service and it has to be re-enabled by hand.", "首次启用，或被系统解绑后需要手动重新打开时用。");
        ZH.put("Four states from one ping plus the state note (no timers): running / just dropped (wakeable, one broadcast brings it back) / long silent (the process went away on its own or is bound but not answering - waking may work, otherwise open DSH Bridge once) / not installed (this install has never been seen alive here).", "四态由**一次 ping 的结果 + 状态记录**判定（不看时间）：运行中 / 刚断（可唤醒，一条广播就能拉回）/ 长时间未响应（进程自己没了，或端口在听却不应答 —— 唤醒可能有效，无效就手动打开一次「DSH 桥」）/ 未安装（这台机器上从没见过它是活的）。");
        ZH.put("Full stop from the app", "App 里的「真停」");
        ZH.put("Fully stop bridge", "真停桥");
        ZH.put("Fully stop the bridge?", "要真停桥吗？");
        ZH.put("Fully stopped; accessibility is off", "已真停；无障碍也关了");
        ZH.put("Idle auto-stop", "闲置自动软停");
        ZH.put("Idle auto-stop is off", "已关闭空闲自动停止");
        ZH.put("Idle auto-stop off: always listening", "闲置自动软停已关：一直监听");
        ZH.put("Idle auto-stop on: soft-stops after 30 idle minutes", "闲置自动软停已开：闲置 30 分钟后自动软停");
        ZH.put("In-app button", "App 里的红色按钮");
        ZH.put("Installed version and whether a newer release exists. If the check fails it says so instead of claiming it is up to date.", "已装版本 + 有没有新发行版。查不到就直说查不到，不谎报「已是最新」。");
        ZH.put("Keeps the notification-bar emergency stop working; with notifications off you lose that rescue path.", "让通知栏的紧急停止可用；关掉通知就少一条自救路径。");
        ZH.put("Language", "语言");
        ZH.put("Lets the App exit and unbinds accessibility. On this vivo it may not be wakeable again - you would have to open DSH Bridge by hand.", "让 App 退出并解绑无障碍。这台 vivo 上可能唤不回来 —— 只能你手动打开「DSH 桥」。");
        ZH.put("Lets the DSH inside Termux operate the phone for you (read screen / tap / swipe / type).\n", "让 Termux 里的 DSH 替你操作这台手机（读屏 / 点击 / 滑动 / 输入）。\n");
        ZH.put("Listening on 127.0.0.1:", "正在监听 127.0.0.1:");
        ZH.put("Maintenance", "维护");
        ZH.put("No browser to open it with; the address is github.com/Maopk/dsh-termux-kit", "没有可用的浏览器；地址是 github.com/Maopk/dsh-termux-kit");
        ZH.put("Not listening", "未监听");
        ZH.put("Notification settings", "通知设置");
        ZH.put("On = DSH may drive the phone through this app (listening on 127.0.0.1:8788). Off = soft stop: the port closes, the process stays, and one broadcast brings it back.", "开 = 允许 DSH 通过本 App 操作手机（监听 127.0.0.1:8788）。关 = 软停：端口关闭、进程保留，一条广播就能拉回。");
        ZH.put("On = soft-stops itself after N idle minutes (less exposure, less battery). Off = always listening.", "开=闲置 N 分钟后自动软停（少暴露、省电）；关=一直监听。");
        ZH.put("Open accessibility settings", "打开无障碍设置");
        ZH.put("Opens github.com/Maopk/dsh-termux-kit - source, releases and docs.", "打开 github.com/Maopk/dsh-termux-kit —— 源码、发行版和文档。");
        ZH.put("Port: ", "端口：");
        ZH.put("Project page", "项目主页");
        ZH.put("Re-read state and resume listening", "重读状态并恢复监听");
        ZH.put("Re-reads the accessibility state from the system and starts listening again if it was soft-stopped.", "从系统重新读无障碍状态；被软停时用它恢复监听。");
        ZH.put("Resumed listening on 127.0.0.1:", "已恢复监听 127.0.0.1：");
        ZH.put("Runs as a foreground service so system/vendor battery savers cannot freeze it and lose contact.", "以前台服务方式常驻，系统/厂商省电策略无法冻结它、导致失联。");
        ZH.put("Security", "安全");
        ZH.put("Settings", "设置");
        ZH.put("Soft-stopped: the port is closed, the process stays, one broadcast brings it back", "已软停：端口关闭、进程保留，一条广播就能拉回");
        ZH.put("Start / Stop", "启动 / 停止");
        ZH.put("Status / Log", "状态 / 日志");
        ZH.put("Stop it", "真停");
        ZH.put("System", "跟随系统");
        ZH.put("System / Chinese / English. The widgets and the page panel follow this too.", "跟随系统 / 中文 / English。小组件和页面面板也跟着变。");
        ZH.put("Tap ① Open accessibility settings and switch DSH Bridge on in the list", "点 ① 打开无障碍设置，在列表里把「DSH 桥」打开");
        ZH.put("The only permissions are accessibility and the local loopback port 127.0.0.1:8788; nothing is uploaded.", "唯一的权限是无障碍和本机回环端口 127.0.0.1:8788；任何内容都不上传。");
        ZH.put("The service is not running right now; to shut it down completely, turn DSH Bridge off in the system accessibility settings", "服务当前未运行；如需彻底关闭，请在系统无障碍设置里关掉「DSH 桥」");
        ZH.put("Token copied; you can paste it to DSH", "token 已复制，可以粘贴发给 DSH");
        ZH.put("Turns accessibility off right now. The same button sits in the notification bar, which is why notifications must stay on.", "立刻关掉无障碍服务。通知栏里有一颗同样的按钮，所以别关通知。");
        ZH.put("Version", "版本");
        ZH.put("Version ", "版本 ");
        ZH.put("accessibility turned off", "无障碍已关闭");
        ZH.put("adb", "adb");
        ZH.put("adb · wireless debugging, needs working Wi-Fi", "adb · 无线调试，需要可用 Wi-Fi");
        ZH.put("bridge · accessibility loopback, no network", "桥 · 无障碍回环，不需要网络");
        ZH.put("done", "完成");
        ZH.put("no bridge APK in the latest release", "最新发行版里没有桥的 APK");
        ZH.put("notification-bar emergency stop", "通知栏紧急停止");
        ZH.put("off ❌", "已关闭 ❌");
        ZH.put("on ✅", "已开启 ✅");
        ZH.put("remote emergency stop received", "收到远程紧急停止指令");
        ZH.put("service destroyed", "服务已销毁");
        ZH.put("sleep command received: fully stopped (no self-recovery)", "收到 sleep 指令：已彻底停止（不会自动恢复）");
        ZH.put("stop command received (remembered: no automatic recovery)", "收到 stop 指令（已记住：不会自动恢复）");
        ZH.put("stopped", "已停止");
        ZH.put("token: ", "token：");
        ZH.put("volume-key emergency stop", "音量键紧急停止");
        ZH.put("★ Emergency stop (any of the four):\n", "★ 紧急停止（四种方式任选）：\n");
        ZH.put("⚠️ Notification permission is off: the notification-bar emergency stop layer is currently dead.", "⚠️ 通知权限被关：通知栏里的那条紧急停止保险目前是失效的。");
        // <<< generated by tools/i18n-table <<<
    }

    private Lang() {}

    static String systemLang() {
        String l = Locale.getDefault().getLanguage();
        return l == null ? "en" : l;
    }

    /** auto follows the system language, otherwise the stored mode wins. */
    static void init(android.content.Context c) {
        try {
            String saved = c.getSharedPreferences("dsh", android.content.Context.MODE_PRIVATE).getString("lang", null);
            if (saved != null) mode = saved;
        } catch (Throwable ignore) {}
        resolve();
    }

    private static void resolve() {
        cur = mode.equals("auto") ? (systemLang().startsWith("zh") ? "zh" : "en") : mode;
    }

    static String mode() { return mode; }
    static boolean isZh() { return cur.equals("zh"); }

    static void setMode(android.content.Context c, String v) {
        if (v.equals("zh") || v.equals("en") || v.equals("auto")) {
            mode = v;
            resolve();
            try {
                c.getSharedPreferences("dsh", android.content.Context.MODE_PRIVATE)
                        .edit().putString("lang", v).apply();
            } catch (Throwable ignore) {}
        }
    }

    static String t(String en) {
        if (!cur.equals("zh") || en == null) return en;
        String z = ZH.get(en);
        return z == null ? en : z;
    }
}
