#!/data/data/com.termux/files/usr/bin/bash
# i18n.sh —— the kit's language layer (shared by the apps, the DSH page panel and the scripts)
#
# Design (added 2026-09-27 when the user asked for a language switch inside the app):
#   · The single source of truth is one file: ~/.dsh-lang, containing a single line: zh / en / auto
#   · Source text everywhere in this repo is **English** (the face of a public repo).
#   · When the user selects Chinese, English strings are mapped back through dsh_msg(); a key that is
#     not in the table is printed AS ENGLISH — a gap never yields an empty line, a key name, or an error.
#     That degradation is deliberate.
#   · auto / missing file → follow the system language (getprop ro.product.locale; measured zh-CN here).
#     ⚠ Do NOT use $LANG: inside Termux it is en_US.UTF-8 by default and says nothing about the user's choice.
#
# Usage:
#   . i18n.sh
#   dsh_lang                 # print the effective language: zh / en
#   dsh_lang_set zh|en|auto  # write ~/.dsh-lang (the app's switch writes the same file)
#   dsh_msg "Some english"   # look the string up for the current language
#
# Maintainers: the table is generated from git history by tools/i18n-build-table (see docs/i18n.md).
# Adding a language needs one more table plus one branch in dsh_msg — nothing else in the codebase.

DSH_LANG_FILE="${DSH_LANG_FILE:-$HOME/.dsh-lang}"

dsh_lang() {
  local v=""
  [ -f "$DSH_LANG_FILE" ] && v=$(head -1 "$DSH_LANG_FILE" 2>/dev/null | tr -d '[:space:]')
  case "$v" in
    zh|en) printf '%s' "$v"; return 0 ;;
  esac
  # auto / unset → follow the system locale
  local sys=""
  if command -v getprop >/dev/null 2>&1; then
    sys=$(getprop persist.sys.locale 2>/dev/null || true)
    [ -z "$sys" ] && sys=$(getprop ro.product.locale 2>/dev/null || true)
  fi
  case "$sys" in
    zh*) printf 'zh' ;;
    *)   printf 'en' ;;
  esac
}

dsh_lang_set() {   # zh|en|auto
  local v="$1"
  case "$v" in
    zh|en|auto) printf '%s\n' "$v" > "$DSH_LANG_FILE"; DSH_LANG_CACHE="$v" ;;
    *) return 1 ;;
  esac
}

# English → Chinese table. Generated by tools/i18n-build-table --write; entries may be added by hand.
# Keys are the exact English source strings (including any ✔/✘ prefix).
declare -A DSH_ZH=(
  ['             the log will state it directly: `error: ... dns resolve failed: couldn']='             日志里会直接写 `error: ... dns resolve failed: couldn'
  ['     sandbox cleanup: 8099 = $P8099 (should be closed); boot log and .dsh-url restored']='     沙箱清理：8099 = $P8099（应为 closed），启动日志与 .dsh-url 已还原'
  ['     ① Termux frozen by the system / the browser froze the background tab — the service is not actually dead
']='     ① Termux 被系统冻结 / 浏览器把后台标签冻结 —— 服务其实没死
'
  ['     ② the long-lived page-to-service connection dropped — the UI stops updating
']='     ② 页面与服务的长连接断了 —— 界面不再更新
'
  ['     ⚠ $w: lock at line ${LK:-none}, action at line ${KW:-none}']='     ⚠ $w：取锁在第 ${LK:-无} 行、动手在第 ${KW:-无} 行'
  ['   (the token is random per process and never written to disk: for an instance you started by hand with dsh web, the token exists only in that terminal)
']='   （token 每次进程随机生成、不落盘：你在终端手动 dsh web 起的实例，token 只在那个终端里）
'
  ['   Both are fixed by **pull-to-refresh on the page**. The login cookie in the browser is signed with a persistent key,
']='   两种都是**下拉刷新页面**就好。浏览器里的登录 cookie 是持久密钥签的，
'
  ['   Note: after an update the version shown in the App may still be the old one (the old process is alive) → cold start it once and look again.
']='   提示：更新后 App 里显示的版本号可能还是旧的（旧进程还活着）→ 冷启动一次再看。
'
  ['   Run: adb tcpip 5555 && adb connect 127.0.0.1:5555']='   执行：adb tcpip 5555 && adb connect 127.0.0.1:5555'
  ['   adb closed it but Chrome is still in front → trying the bridge']='   adb 关了但前台仍是 Chrome → 试试借桥'
  ['   all good ✅
']='   有故障 ❌ —— 上面带 ✘ 的那一步就是原因
'
  ['   connect target: $CONN']='   连接目标: $CONN'
  ['   fault found ❌ — the step marked ✘ above is the cause
']='   取证办法：Clash → 日志 → 「Clash 日志捕捉工具」→ 点此启动（info 级）→ 再复现一次，
'
  ['   pairing service: $PAIR']='   配对服务: $PAIR'
  ['   so it stays valid after a DSH restart and normally you never need a new token URL.
']='   重启 DSH 之后依然有效，所以正常情况下你根本不需要重新拿 token URL。
'
  ['   · bridge did not respond (it probably was not running)']='   · 桥没响应（可能本来就没在跑）'
  ['   · bringing the DSH window to the front (so Back can be sent to it)']='   · 把 DSH 窗口带到前台（这样才能给它发返回键）'
  ['   · brought $prev back to the front']='   · 已把 $prev 拉回前台'
  ['   · no token file (it was never authorized)']='   · 没有 token 文件（本来就没授权过）'
  ['   · skipped (PANIC_NO_UI=1, self-test only)']='   · 已跳过（PANIC_NO_UI=1，仅自检用）'
  ['   ✔ bridge received panic: port closed + accessibility shut itself down']='   ✔ 桥已收到 panic：端口关闭 + 无障碍已自行关闭'
  ['   ✔ ended $KILLED related processes']='   ✔ 已结束 $KILLED 个相关进程'
  ['   ✔ window closed (pressed Back $((i-1)) times)']='   ✔ 窗口已关（按了 $((i-1)) 次返回键）'
  ['   ✘ integrity check failed (the compressed stream is truncated or corrupt)']='   ✘ 完整性检查失败（压缩流被截断或损坏）'
  ['   ✘ the bridge did not answer (--fast); cannot press keys through it']='   ✘ 桥没应答（--fast），无法借它按键'
  ['  cleared %d old entries']='  清掉旧条目 %d 条'
  ['  entered: %s']='  已进入: %s'
  ['  {data.get(']='  共 {data.get('
  ['  {p}: no response ({e.__class__.__name__})']='  {p}: 无响应 ({e.__class__.__name__})'
  ['  ✔ %s = %d entries']='  ✔ %s = %d 个条目'
  [' (dry-run, nothing changed)']='（dry-run，未改动）'
  [' a switch (or is not wired to the helper)']='做成开关（或没接上 helper）'
  [' replaced with ']=' 已替换为 '
  ['# DSH full snapshot · restore instructions']='# DSH 完整快照 · 还原说明'
  ['# DSH plugin list snapshot']='# DSH 插件清单快照'
  ['## Notes']='## 说明'
  ['## Restore steps (install the same Termux version first; no root needed)']='## 还原步骤（先装同版本 Termux，无需 root）'
  ['$DRY']='⑤ 走「锁屏密码验证」→ 数字键盘'
  ['$FAIL']='   一切正常 ✅
'
  ['$T/8_enable-wireless-adb.sh']='$T/8_自动开无线调试.sh'
  ['$TMPLOG']='开关已置 1|已是开启|已连上'
  ['${1:?Usage: dsh-browser-open <url>}']='${1:?用法: dsh-browser-open <url>}'
  ['${2:?apk path}']='${2:?apk 路径}'
  ['${2:?keyword}']='${2:?关键词}'
  ['${2:?package}']='${2:?包名}'
  ['${2:?pairing port}']='${2:?配对端口}'
  ['${3:?pairing code}']='${3:?配对码}'
  ['${DRY:-0}']='   · [dry] 发布状态到 Download/dsh/状态/
'
  ['%d hits in total']='共 %d 处'
  ['%d whitelisted components ✔']='白名单 %d 个组件 ✔'
  ['(dry-run)']='   · [dry] 点「锁屏密码验证」→ 按 6 位数字
'
  ['(dry-run) authorized: a real run can read the password']='（dry-run）已授权：真跑能读到密码'
  ['(none)']='（无）'
  ['(timeout 300s)']='(超时 300s)'
  [') bytes)']=') 字节)'
  [')); url_ready correctly calls it unusable']=')），url_ready 正确判为不可用'
  [')} nodes']=')} 个节点'
  [', as before)']='就退出）'
  ['- excluded: storage/ (your phone storage), ~/.smoke (cache), ~/.npm, ~/.cache, ~/.dsh/profiles.bak-*.']='- 不含：storage/（你的手机存储）、~/.smoke（缓存）、~/.npm、~/.cache、~/.dsh/profiles.bak-*。'
  ['- the archive holds only absolute /data/data/com.termux/... paths; owner is recorded as 0 and unpacks as the current Termux UID when not root.']='- 归档里全是 /data/data/com.termux/... 的绝对路径；owner 记作 0，解包时非 root 会自动落成当前 Termux 的 UID。'
  ['- ⚠ credentials (.credentials.yaml, bridge token) are **inside the archive** — this is a full snapshot, so treat it as a sensitive file.']='- ⚠ 凭据（.credentials.yaml、桥 token）**在包内** —— 这是完整快照，请当敏感文件保管。'
  ['--- result ---']='--- 结果 ---'
  ['--brief ${BRIEF}B (full ${FULL}B): status stays whole, only task output is tail-truncated']='--brief ${BRIEF}B（完整 ${FULL}B）：状态整包不切头，任务输出才从尾部截'
  ['--brief ${BRIEF}B already exceeds 4000 and will be truncated (needs slimming)']='--brief ${BRIEF}B 已超 4000，会被截断（要给它瘦身）'
  ['0_emergency-stop']='0_紧急停止'
  ['0_emergency-stop.sh']='0_紧急停止.sh'
  ['1_start-dsh']='1_启动DSH'
  ['1_start-dsh.sh cold start']='1_启动DSH.sh 冷启动'
  ['2_shutdown-dsh']='2_关闭DSH'
  ['2_shutdown-dsh.sh']='2_关闭DSH.sh'
  ['3_backup-dsh']='3_备份DSH'
  ['4_soft-restart-dsh']='4_软重启DSH'
  ['4_soft-restart-dsh.sh']='4_软重启DSH.sh'
  ['5_cleanup-dsh']='5_清理DSH'
  ['6_hard-restart-dsh']='6_硬重启DSH'
  ['6_hard-restart-dsh.sh']='6_硬重启DSH.sh'
  ['7_reconnect-ai']='7_重连AI通道'
  ['8080 is not running, cannot verify']='8080 没在跑，无法验证'
  ['8_enable-wireless-adb']='8_自动开无线调试'
  ['8_enable-wireless-adb.sh']='8_自动开无线调试.sh'
  ['9_revoke-pin']='9_撤销密码授权'
  ['9_revoke-pin alongside bridge_wake/bridge_status are both whitelisted']='9_撤销密码授权 与 bridge_wake/bridge_status 都在白名单里'
  ['; other node processes untouched)']=' 匹配，不动别的 node）'
  ['<js expression>']='<js 表达式>'
  ['<raw JSON command>']='<原始 JSON 命令>'
  ['== key versions ==']='== 关键版本 =='
  ['== size of each part ==']='== 各部分体积 =='
  ['@deepseek-ai/dsh-base / dsh-web-app are both present (after pnpm install, dsh-relink-bundles restores the links)']='@deepseek-ai/dsh-base / dsh-web-app 都在（pnpm install 后要 dsh-relink-bundles 补链）'
  ['Another startup is already in progress (lock held by pid $(boot_lock_owner)) — wait for it to finish, do not tap twice']='另一个启动正在进行中（锁持有者 pid $(boot_lock_owner)）——等它跑完再试，别连点'
  ['Clash could not open even GitHub']='Clash 连 GitHub 都打不开'
  ['Create one entry and write value into it; returns whether the confirm succeeded.']='新建一条并写入 value，返回是否确认成功。'
  ['DSH is alive ($DSH_PORT listening), but I do not have the token for this run']='DSH 活着（$DSH_PORT 在听），只是我这边没有它本次的 token'
  ['DSH is alive and the auth URL is valid (HTTP 200)']='DSH 活着，认证 URL 也有效（HTTP 200）'
  ['DSH is not running']='DSH 没在跑'
  ['DSH status  %s']='DSH 状态  %s'
  ['Delete every existing entry in the list (each removal shifts the rows below up by one row height).']='把列表里已有条目全删掉（每删一条，后面的行会上移一个行高）。'
  ['No usable auth URL within ${t}s']='${t} 秒内没等到可用的认证 URL'
  ['No ~/.dsh-bridge-token (revoked?) → weak wake only: it cannot wake an already stopped service']='没有 ~/.dsh-bridge-token（被吊销过？）→ 只能弱唤醒：服务已关时唤不醒'
  ['Note: dsh-install-pass is now dsh-auth-pass (meaning: may the AI use your password, not only for installs)
']='注意：dsh-install-pass 已改名为 dsh-auth-pass（语义：AI 能否动用你的密码，不只安装）
'
  ['Note: session archives were not scanned. The current session is still writing back → run --all again after the session ends for a complete scrub.']='提示：未扫描会话存档。当前会话仍在写回 → 要在会话结束后再跑一次 --all 才彻底。'
  ['PWA pkg    : ${PWA:-not found, dsh-browser-open has not written a cache yet}']='PWA 包名   : ${PWA:-（未发现，dsh-browser-open 还没写过缓存）}'
  ['Readiness check passed: the auth URL returns 200 after redirects']='就绪校验通过：认证 URL 跟随跳转返回 200'
  ['Report only whether authorization exists (helper status never echoes the password).']='只看授权存续（helper 的 status 从不回显密码）。'
  ['Return [{x,y,cls,text,desc}]; the coordinates are content coordinates.']='返回 [{x,y,cls,text,desc}]，坐标为内容坐标。'
  ['Self-check: ls -l $DIR ; cat $DIR/bridge.log | tail -5']='自检：ls -l $DIR ; cat $DIR/bridge.log | tail -5'
  ['The process exited during startup (most likely the plugin tree failed to load)']='进程在启动过程中退出了（多半是插件树加载失败）'
  ['Timeout: no screenshot arrived. Check ① whether plugin look-1 is approved and running ② whether the DSH page is open in a browser']='超时：未收到截图。请检查 ① 插件 look-1 是否已批准运行 ② DSH 页面是否在浏览器中打开'
  ['Title of the dialog: the TextView at y≈265; returns None when no dialog is open.']='对话框标题：y≈265 的 TextView；没有对话框时返回 None。'
  ['Title:']='标题:'
  ['UI tree saved: $HOME/.droid-ui.xml ($(wc -c < ']='UI 树已存: $HOME/.droid-ui.xml ($(wc -c < '
  ['Usage: dsh-auth-pass status|set|revoke|digits|path
']='用法: dsh-auth-pass status|set|revoke|digits|path
'
  ['Usage: dsh-control swipe <from> <to> [steps]  (selector / x,y / text=<text>)']='用法: dsh-control swipe <起点> <终点> [步数]  （选择器 / x,y / text=文字）'
  ['Usage: dsh-eval <js file> | dsh-eval -']='用法: dsh-eval <js文件> | dsh-eval -'
  ['Wi-Fi is off']='Wi-Fi 关着'
  ['Wi-Fi is off → the script correctly stops early (preconditions unmet, not a widget problem)']='Wi-Fi 关着 → 脚本正确提前停下（前置不满足，非组件问题）'
  ['Write the 6 digits. **Note: no logging, no echo, no field in any response.**']='写入 6 位密码。**注意：不记日志、不回显、不放进任何响应字段。**'
  ['[L0] Preconditions']='【L0】前置条件'
  ['[L1] Syntax check']='【L1】语法检查'
  ['[L2] --dry-run full-flow rehearsal']='【L2】--dry-run 全流程预演'
  ['[L3] Readiness check and boot lock (regression tests)']='【L3】就绪判定与启动锁（回归测试）'
  ['[L4] Real runs (safe and reversible)']='【L4】真实执行（安全可逆的）'
  ['[SKIP] A real run would kill this session or needs manual recovery']='【SKIP】真跑会杀掉当前会话或需人工恢复'
  ['
   [Do not restart yet] that cannot-read-after-redirect is usually one of these:
']='
   【先别重启】你说的「跳转回来无法读取」通常是这两种：
'
  ['
   dsh-restart --force is needed only when it still will not open after a refresh
']='
   只有「刷新后仍然打不开」才需要：dsh-restart --force
'
  ['
  now just refresh the browser page (the login cookie stays valid across a restart).
']='
  现在刷新一下浏览器页面即可（浏览器里的登录 cookie 在重启后依然有效）。
'
  ['
Note: after re-linking, just **refresh the page** (no DSH restart needed — the route assembles the bundle per request).
']='
提示：补链后**刷新页面**即可（不必重启 DSH —— 路由是按请求现拼 bundle 的）。
'
  ['
wrote: %s']='
已写入: %s'
  ['a Switch in the maintenance class: on = the AI may use your password to pass verification, off = revoked at once (not just for installs)']='维护类里是 Switch：开=AI 可动用你的密码过验证，关=立刻收回（语义不只装包）'
  ['a real run restarts the service and drops this session']='真跑会重启服务、断开当前会话'
  ['a real run revokes the token + disables accessibility + drops adb and needs manual recovery; indirectly verified by the volume-key drill']='真跑会吊销 token + 关无障碍 + 断 adb，需你手动恢复；已由音量键演练间接验证'
  ['a real run stops this session; every step has been run for real on its own (backup/rotation/port wait/bridge stop), and window closing was run for real via dsh-close-window']='真跑会停掉当前会话；各步骤已单独真跑（备份/轮换/端口等待/桥停），关窗口由 dsh-close-window 单独真跑过'
  ['adb        : $(adb_ready && echo connected || echo not connected)']='adb        : $(adb_ready && echo 已连接 || echo 未连接)'
  ['adb is not connected']='adb 没连上'
  ['already there: Download/dsh/$c/$(basename ']='已在位: Download/dsh/$c/$(basename '
  ['asked the installer to open it']='已请求安装器打开'
  ['auth set rc=%s (the value never enters the log)']='auth set rc=%s (值不入日志)'
  ['backup done: $NAME ${SIZE:-}']='备份完成: $NAME ${SIZE:-}'
  ['bash ~/.shortcuts/tasks/1_start-dsh.sh']='bash ~/.shortcuts/tasks/1_启动DSH.sh'
  ['boot exclusion lock']='启动互斥锁'
  ['bridge capability probe']='桥能力探测'
  ['bridge is awake']='桥已唤醒'
  ['bridge soft stop/wake']='桥软停/唤醒'
  ['bridge will not start']='桥起不来'
  ['bridge: not listening (8788 closed)
']='桥：未监听（8788 关闭）
'
  ['bridge: the port listens but does not answer (likely frozen by the system) → try dsh-bridge wake
']='桥：端口在听但不答应（多半被系统冻结）→ 建议 dsh-bridge wake
'
  ['broadcast + UI raise']='端口在听但服务被冻结'
  ['broadcast + raise UI']='广播+拉界面'
  ['cannot create the sandbox file $TMPPASS']='造不出沙箱文件 $TMPPASS'
  ['cannot read the local token']='读不到本机 token'
  ['categories + bridge/adb split + password-rights switch; tasksd serves /auth too']='分类 + 桥/adb 分开 + 密码使用权开关；tasksd 也接了 /auth'
  ['chromium is not installed: pkg install chromium']='chromium 未安装：pkg install chromium'
  ['client bundle really fetches']='客户端 bundle 真能取'
  ['close DSH']='关闭 DSH'
  ['close action tells the truth']='关闭动作不撒谎'
  ['closed']='已关闭'
  ['closest to the viewport center']='离视口中心最近'
  ['command: $JSON']='命令: $JSON'
  ['components (last result)']='组件（上次结果）'
  ['depends on the bridge channel; preconditions unmet']='依赖桥通道，前置未满足'
  ['depends on the bridge channel; preconditions unmet (not a widget problem)']='依赖桥通道，前置未满足（非组件问题）'
  ['did the last run succeed']='上次跑成没成功'
  ['droid-sock sleep does not respond']='droid-sock sleep 无响应'
  ['droid-sock stop does not respond']='droid-sock stop 无响应'
  ['dry run passed']='预演成功'
  ['dsh-tasksd listening on 127.0.0.1:%d (token: %s)']='dsh-tasksd 监听 127.0.0.1:%d（token: %s）'
  ['entered $i digits']='已输入 $i 位'
  ['env: Wi-Fi is not on a network → wireless debugging reset to 0 (correctly diagnosed, no futile scan)']='环境：Wi-Fi 没连上网络 → 无线调试清回 0（已正确诊断，未白扫端口）'
  ['env: Wi-Fi is on but not on a network → the system reset wireless debugging to 0 (correctly diagnosed)']='环境：Wi-Fi 开着但没连上网络 → 系统把无线调试清回 0（已正确诊断）'
  ['env: switch=1 but the framework never started; enable it manually once in Developer options (correctly diagnosed)']='环境：开关=1 但框架未启动，需在开发者选项手动开一次（已正确诊断）'
  ['env: the network is fine but the system reset the switch to 0 → enable it manually once in Developer options (correctly diagnosed, no futile scan)']='环境：网络通但开关被系统清回 0 → 需在开发者选项手动开一次（已正确诊断，未白扫端口）'
  ['exit $RC8 (see $TMPLOG)']='退出 $RC8（见 $TMPLOG）'
  ['exit $RCR / the file is still there: $OUTR']='退出 $RCR / 文件仍在：$OUTR'
  ['exit 0 but the switch never took effect (see $TMPLOG)']='退出 0 但没看到开关生效（见 $TMPLOG）'
  ['exit 1 with no diagnosis given (see $TMPLOG)']='退出 1 且没能给出诊断（见 $TMPLOG）'
  ['extra packages']='多余的包'
  ['file contents are not 6 digits; refusing to print
']='文件内容不是 6 位数字，拒绝输出
'
  ['foreground : ${FG:-bridge did not answer}']='前台包名   : ${FG:-（桥没应答）}'
  ['foreground package']='前台包名'
  ['found {len(found)} (pairing=pairing port, connect=connect port)']='共发现 {len(found)} 个（pairing=配对端口，connect=连接端口）'
  ['general system-auth credential']='系统身份验证的通用凭据'
  ['generated: $(date ']='生成时间: $(date '
  ['grows on a real machine']='长在实际机器上'
  ['half-start evidence']='半启动取证'
  ['half-started 404 rejected']='半启动 404 被拒'
  ['has a desktop']='有桌面'
  ['helper missing, or widget 9 is not wired to revoke']='缺 helper 或组件 9 没接上 revoke'
  ['hit %d files:']='命中 %d 个文件：'
  ['install complete ($VER)']='安装完成（$VER）'
  ['is the window still there']='窗口还在不在'
  ['is there a desktop']='有没有桌面'
  ['it broke again']='这次又有问题'
  ['it did not come back within 15s (self-recovery depends on when the system rebinds accessibility; it does not always trigger)']='15 秒内没有自己回来（自恢复取决于系统何时重绑无障碍，不是每次都触发）'
  ['kill any dsh process that was not in the pre-boot snapshot']='凡是不在启动前快照里的 dsh 进程就 kill'
  ['links missing → the page reports Failed to load plugins (run dsh-relink-bundles)']='缺链 → 页面会报 Failed to load plugins（跑 dsh-relink-bundles）'
  ['listening ports:']='监听端口:'
  ['lock is held (another instance is running); left alone']='锁被占用（还有实例在跑），未动'
  ['missing the Wi-Fi handoff flow (would exit after only reporting ']='缺 Wi-Fi 交接流程（会像以前那样只报'
  ['missing the read-back check (would scan 30k ports and give a cause opposite to the facts)']='缺回读校验（会白扫 3 万端口并给出与事实相反的原因）'
  ['never finished the real readiness check (exit=$WRC, see $TMPLOG)']='没有走完真就绪校验（exit=$WRC，见 $TMPLOG）'
  ['no /plugins/ URL parsed from the page (DSH may have just started)']='页面里没解析出 /plugins/ URL（DSH 可能刚起）'
  ['no DSH process (you may have killed it already)']='没有 DSH 进程（可能已经被你 kill 了）'
  ['no URL in .dsh-url']='.dsh-url 里没有 URL'
  ['no leftover lock']='没有残留锁'
  ['not blocked']='没挡住'
  ['not executed: preconditions unmet']='未执行：前置不满足'
  ['not open']='未打开'
  ['one-click run']='一键跑组件'
  ['orphan credentials lock']='孤儿 credentials 锁'
  ['orphan lock cleared']='清掉了孤儿锁'
  ['password-rights switch (console)']='密码使用权开关(控制台)'
  ['paused flag correct']='paused 标记正确'
  ['paused is back to false after the wake (the next rebind will not be silenced)']='唤醒后 paused 已清回 false（下次重绑不会被静默）'
  ['paused is still true after the wake ($PS)']='唤醒后 paused 仍是 true（$PS）'
  ['port %d can be bound ✔']='端口 %d 可绑定 ✔'
  ['port %d failed to bind: %s']='端口 %d 绑定失败: %s'
  ['process exited during startup']='进程在启动过程中退出了'
  ['real authorisation untouched']='真授权未被误删'
  ['real run passed (idempotent)']='真跑通过（幂等）'
  ['really gone']='确实没了'
  ['refresh does nothing']='点了刷新刷不出来'
  ['removed with no instance, left alone with one (no permanent boot hang after -9)']='无实例时删除；有实例时不动（-9 之后不再永久卡启动）'
  ['restriction']='设置限制'
  ['revoke password rights (real run)']='收回密码使用权(真跑)'
  ['revoke password rights (widget)']='收回密码使用权(小组件)'
  ['runtime bundle symlinks']='运行时 bundle 软链'
  ['same as above; this is the only way to verify the -9 hard-kill path (orphan lock cleanup is covered by the L3 (5) unit test)']='同上；这是唯一能验证 -9 强杀路径的方式（孤儿锁清理已由 L3⑤ 单测覆盖）'
  ['sampled HTTP code sequence: ${SEQ:-(none sampled; startup may have been too fast)}']='采样到 HTTP 码序列：${SEQ:-（没采到，可能启动过快）}'
  ['sampled HTTP code sequence: ${SEQ} (401=auth mounted but no token; the old logic called that ready too)']='采样到 HTTP 码序列：${SEQ}（401=认证已挂但无 token，旧逻辑也当成就绪）'
  ['sampled HTTP code sequence: ${SEQ} (404=routes not mounted yet; the old logic would open the browser right here)']='采样到 HTTP 码序列：${SEQ}（404=路由还没挂，旧逻辑此时就会开浏览器）'
  ['screenshot failed (try: DSH_LOOK_WAIT_MS=25000 dsh-look)']='截图失败（可试：DSH_LOOK_WAIT_MS=25000 dsh-look）'
  ['screenshot requested, waiting for the result (up to ${WAIT}s)…']='已触发截图请求，等待结果（最多 ${WAIT}s）…'
  ['screenshot saved: %s (%.1f KB)']='已截图: %s (%.1f KB)'
  ['selector / x,y coordinate / text=<text> → gesture start and end']='选择器 / x,y 坐标 / text=文字 → 手势起终点'
  ['soft stop self-recovery']='软停自恢复实测'
  ['soft stop → broadcast wake round trip succeeded']='软停→广播唤醒 往返成功'
  ['stale off-screen copy']='屏幕外的旧副本'
  ['stale token rejected']='旧 token 被拒'
  ['start complete']='启动完成'
  ['status pushback not truncated']='状态回传不截断'
  ['t find ip` — that kind of cause
']='t find ip` 这类原因
'
  ['taps the keypad digit by digit']='逐位点数字键盘'
  ['tar -I zstd -xf <this file> -C /']='tar -I zstd -xf <这个文件> -C /'
  ['task plugin (page) updated']='task 插件(页面)更新'
  ['tasksd started, listening on 127.0.0.1:%d']='tasksd 启动，监听 127.0.0.1:%d'
  ['tasksd whitelist+virtual tasks']='tasksd 白名单+虚拟任务'
  ['the 404 server is correctly rejected (old check: http_code=$OLD)']='404 服务被正确拒绝（旧判定 http_code=$OLD）'
  ['the AI may use your lockscreen password']='AI 可以动用你的锁屏密码'
  ['the AI uses your lock-screen password to install packages']='AI 拿你的锁屏密码装包'
  ['the app side does not distinguish status/task truncation rules (status JSON gets its head cut)']='App 侧没有区分 status/任务的截断规则（状态 JSON 会被切头）'
  ['the bridge is down']='桥没起来'
  ['the bridge was already answering; no wake needed']='桥本来就在应答，无需唤醒'
  ['the bundle really fetches']='真的能取到 bundle'
  ['the cached URL happens to still be valid (200)']='缓存 URL 恰好仍有效（200）'
  ['the cached URL is dead (HTTP $(url_code ']='缓存 URL 已失效（HTTP $(url_code '
  ['the console does not make ']='控制台里没有把'
  ['the first broadcast did not bring it back within 45s; the extra one recovered it at ${BACK}s (slow vivo cold start, a known jitter)']='首发 45s 没回，补一发后 ${BACK}s 恢复（vivo 冷启动慢，属已知抖动）'
  ['the local 8080 is not running']='本机 8080 没在跑'
  ['the lock exists but cannot be deleted']='锁存在但删不掉'
  ['the old check would let HTTP $OLD through → the new one blocks it (this is the 404 from the screenshot)']='旧判定看到 HTTP $OLD 会放行 → 新判定正确拦住（这就是截图那个 404）'
  ['the plugin or tasksd lags behind (one of categories/switch/auth endpoint is missing)']='插件或 tasksd 没跟上（分类/开关/授权端点缺一）'
  ['the port is back ${BACK}s after the broadcast wake (the process is alive, no re-authorisation needed)']='广播唤醒后 ${BACK}s 端口恢复（进程还活着，不用重新授权）'
  ['the port is still open after sleep']='sleep 后端口仍开'
  ['the port is still open after stop']='stop 后端口仍开'
  ['the port is still open after the soft stop']='软停后端口仍开'
  ['the provider was down']='机场挂了'
  ['the sandbox file is overwritten then removed, exit 0; $OUTR']='沙箱文件先覆写后删除，退出 0；$OUTR'
  ['the second boot was not blocked → two rapid taps pull up two instances']='第二个启动没被挡住 → 连点两次会拉起两个实例'
  ['the selftest deleted the real authorisation file (the one thing that must never happen)']='自检把真授权文件删了（这正是最不能出的事）'
  ['the whitelist lags behind (missing 9_ or the bridge']='白名单没跟上（缺 9_ 或桥的虚拟任务）'
  ['the window closes at line $CW, the bridge stops only at line $BSTOP (reversed, it can never close without adb)']='第 $CW 行关窗口、第 $BSTOP 行才停桥（顺序反了就没 adb 一定关不掉）'
  ['there is no authorisation file right now (not authorised)']='当前没有授权文件（未授权状态）'
  ['this host has no usable desktop…']='此主机没有可用的桌面…'
  ['this is an old bridge: soft stop only (closes the port) and it returns whenever the system rebinds accessibility → installing v1.7 fixes it properly']='当前是旧版桥：只能软停（关端口），系统重绑无障碍时会自己回来 → 装 v1.7 可根治'
  ['token file: %s (%s…)']='token 文件: %s (%s…)'
  ['two broadcasts and 90 seconds still did not wake it']='两发广播共 90 秒没唤回来'
  ['two taps → two instances fight over the write lock → one crashes']='连点两次 → 两个实例抢写锁 → 崩一个'
  ['unavailable']='不可用'
  ['unknown argument %s
']='未知参数 %s
'
  ['unknown argument: $1']='未知参数: $1'
  ['unknown usage']='未知用法'
  ['unknown usage: ']='未知用法: '
  ['url_ready actually treated 404 as ready']='url_ready 竟然把 404 当成就绪'
  ['v1.7 real stop']='v1.7 真停'
  ['v1.7+ supports a real sleep stop + a token-bearing wake can re-authorise']='v1.7+ 支持 sleep 真停 + 带 token 唤醒可重新授权'
  ['v1.8 soft stop durable']='v1.8 软停持久'
  ['v1.8 wake recovery']='v1.8 唤醒恢复'
  ['value to scrub']='要清的值'
  ['wake broadcast sent']='已发送唤醒广播'
  ['wake failed (open the app or install v1.7)']='唤醒失败（需打开 App 或装 v1.7）'
  ['which App you were using before closing']='关窗口之前你在用哪个 App'
  ['widget 2 never calls bare am force-stop; without adb dsh-close-window borrows the bridge to send keys (device-verified 2026-09-27: one Back key closes it)']='组件 2 不裸用 am force-stop；没 adb 时交给 dsh-close-window 借桥按键（2026-09-27 实机验证：1 次返回键即关闭）'
  ['widget 2 still has $BADFS bare am force-stop calls (termux-am lacks it → reports success without closing)']='组件 2 里还有 $BADFS 处裸 am force-stop（termux-am 不支持 → 没关却报成功）'
  ['widget8 Wi-Fi handoff']='组件8 Wi-Fi 半自动'
  ['widget8 read-back after set']='组件8 置1后先回读'
  ['window close ($CW) does not come before bridge stop ($BSTOP) → the bridge is down and nobody can send keys']='关窗口($CW) 没有排在停桥($BSTOP) 之前 → 桥已停，按键无人可借'
  ['window close before bridge stop']='关窗口早于停桥'
  ['wizard closed (the installer exited) → leaving the verdict to the verification step']='向导已关闭（安装器退出）→ 交给下一步的复核判定'
  ['wrong behaviour (no instance=$R1 removed=$GONE with instance=$R2)']='行为不对（无实例=$R1 删掉了=$GONE 有实例=$R2）'
  ['wrote: %s -> %s']='已写入: %s -> %s'
  ['you passed --force; restarting anyway']='你加了 --force，继续重启'
  ['zeroconf unavailable: pip install zeroconf']='zeroconf 不可用：pip install zeroconf'
  ['{hits} matches (the coordinates are the tap center)']='共 {hits} 个匹配（坐标即点击中心）'
  ['→ closing via adb']='→ 走 adb 关闭'
  ['→ closing via the bridge (accessibility)']='→ 走桥关闭（无障碍）'
  ['→ waking the bridge (broadcast with token)…
']='→ 唤醒桥（带 token 的广播）…
'
  ['⏱ Timeout: the bridge script does not seem to be running. Open /sdcard/dsh-droid/bridge.js in AutoX.js and tap run.']='⏱ 超时：桥接脚本似乎没在运行。请在 AutoX.js 里打开 /sdcard/dsh-droid/bridge.js 并点运行。'
  ['⏱ timeout ${TIMEOUT}s: the page did not respond (not open / not refreshed to the new client)']='⏱ 超时 ${TIMEOUT}s：页面未响应（未打开 / 未刷新到新版客户端）'
  ['① end the DSH processes (matched only by ']='① 结束 DSH 进程（只按 '
  ['① looking for the pairing port (mDNS, up to 22s)…']='① 找配对端口（mDNS，最多 22 秒）…'
  ['① precondition check']='① 前置检查'
  ['① skipping pairing, reconnecting directly']='① 跳过配对，直接重连'
  ['① using the pairing port you gave: $PAIR']='① 使用你给的配对端口: $PAIR'
  ['② clear the orphan credentials lock (after a -9 it makes the next start fail for sure)']='② 清理孤儿 credentials 锁（-9 之后它会让下次启动必然失败）'
  ['② direct domestic link and DNS hijack are healthy']='② 直连（国内）与 DNS 劫持是否正常'
  ['② open the package (copied to an ASCII path to avoid Chinese-URI encoding problems)']='② 打开安装包（复制成 ASCII 路径，避免中文 URI 编码问题）'
  ['② pairing (code $CODE)']='② 配对（配对码 $CODE）'
  ['② revoking the token']='② 吊销 token'
  ['③ can traffic go through a node (proxy)']='③ 走节点（代理）通不通'
  ['③ clearing the shared-directory command channel (AutoX bridge)']='③ 清空共享目录指令通道（AutoX 桥）'
  ['③ keep the previous URL in .dsh-url (saved before the log is cleared)']='③ 保留上一轮的 URL 到 .dsh-url（清日志前先存）'
  ['③ looking for the connect port …']='③ 找连接端口 …'
  ['③ retention (full snapshots keep only the newest $KEEP)']='③ 保留策略（完整快照只留最近 $KEEP 份）'
  ['④ device state']='④ 设备状态'
  ['④ done in $(( $(date +%s) - T0 ))s']='④ 完成，用时 $(( $(date +%s) - T0 ))s'
  ['④ ending waiting/looping processes on my side']='④ 结束我这边的等待/循环进程'
  ['④ start and wait for **real readiness** (token line + following the redirect to 200)']='④ 启动并等**真就绪**（token 行 + 跟随跳转 200）'
  ['④ was the node domain eaten by fake-ip (the nastiest one: direct works, all proxies 502)']='④ 节点域名有没有被 fake-ip 吃掉（这条最坑：直连正常、代理全 502）'
  ['⑤ Verdict']='⑤ 结论'
  ['⑤ opening the accessibility settings page']='⑤ 打开无障碍设置页'
  ['⑤ verify shell']='⑤ 验证 shell'
  ['⚠ Chrome is unavailable too; handing over to the system default (a chooser may pop up)']='⚠ Chrome 也不可用，交给系统默认（可能弹选择框）'
  ['⚠ still missing from bundles: ']='⚠ bundles 里还缺：'
  ['✅ wireless debugging channel is up. Optional next step: fix the port (works with Wi-Fi off, until reboot)']='✅ 无线调试通道打通。接下来可选：固定端口（关掉 Wi-Fi 也能用，重启前有效）'
  ['✔ all %d entries of the bundles list are in place']='✔ bundles 清单 %d 个全部就位'
  ['✔ closed (adb): the browser/PWA window is gone']='✔ 已关闭（adb）：浏览器/PWA 窗口已消失'
  ['✔ no URL-style tokens
']='✔ 没有 URL 形式的 token
'
  ['✔ no keystore/private-key files
']='✔ 没有密钥库/私钥文件
'
  ['✔ no private-key material
']='✔ 没有私钥内容
'
  ['✔ opened in the standalone DSH window ($1${SERIAL:+ · via adb})']='✔ 已在 DSH 独立窗口打开（$1${SERIAL:+ · 经 adb}）'
  ['✘ cannot open field: %s']='✘ 打不开字段: %s'
  ['✘ cannot open field: %s (current title %s)']='✘ 打不开字段: %s（当前标题 %s）'
  ['✘ could not close it. Alternatives: ① swipe it away from recents by hand; ② turn on wireless debugging once so I can close it with adb']='✘ 没关掉。可行的替代：① 手动从最近任务划掉；② 开一次无线调试让我用 adb 关'
  ['✘ failed to write the status file: %s']='✘ 写状态文件失败: %s'
  ['✘ not found or not tappable: %s']='✘ 找不到/点不到: %s'
  ['✘ repo contains keystore/private-key files (should be excluded)
']='✘ 仓库里有密钥库/私钥文件（应当排除）
'
  ['✘ repo contains private-key material
']='✘ 仓库里有私钥内容
'
  ['✘ repo contains token=<long string> style values (listed above)
']='✘ 仓库里出现形如 token=<长串> 的内容（上面已列出）
'
  ['✘ write failed: %s']='✘ 写入失败: %s'
  ['✘ wrong entry count: expected %d, got %d']='✘ 条目数不对：期望 %d，实际 %d'
  ['❌ bridge did not answer (--fast, no wake): %s']='❌ 桥没应答（--fast，未唤醒）：%s'
  ['❌ no connected device. Run first: droid conn <port> (or droid conn pair <port> <code>)']='❌ 没有已连接的设备。先跑：droid conn <端口>（或用 droid conn pair <端口> <配对码>）'
  ['❌ no pairing service found. You can pass the ports by hand: droid-pair <code> <pairing port>']='❌ 没发现配对服务。可以改成手工指定端口：droid-pair <配对码> <配对端口>'
  ['❌ no response']='❌ 没有响应'
  ['❌ no token']='❌ 没有 token'
)

dsh_msg() {
  local s="$1"
  if [ -z "${DSH_LANG_CACHE:-}" ]; then DSH_LANG_CACHE="$(dsh_lang)"; fi
  [ "$DSH_LANG_CACHE" = "zh" ] || { printf '%s' "$s"; return 0; }
  printf '%s' "${DSH_ZH[$s]:-$s}"
}
