package io.dsh.console;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Tiny built-in two-language table (named Lang, not L: MainActivity has a local JSONObject called L).
 *
 * Why not the Android way: this app is built with plain javac + android.jar, so there is no
 * AndroidX and therefore no AppCompatDelegate.setApplicationLocales(). A small table plus a
 * preference (and recreate()) gives the same result with zero dependencies.
 *
 * The switch writes the SAME file the shell scripts read - ~/.dsh-lang - so the app, the DSH page
 * panel and the 10 widgets never disagree about the current language. That file lives in Termux's
 * private directory, which this app cannot touch directly, so it is written by running
 * "dsh-lang set <v>" through the RUN_COMMAND channel instead.
 *
 * A key that is missing returns the English string unchanged, so a gap shows one English line
 * rather than an empty label.
 */
final class Lang {
    static final String LANG_FILE = "/data/data/com.termux/files/home/.dsh-lang";
    static final String[] MODES = {"auto", "zh", "en"};
    private static final Map<String, String> ZH = new HashMap<>();
    private static String mode = "auto";
    private static String cur = "en";

    static {
        // >>> generated by tools/i18n-table — do not edit by hand >>>
        ZH.put("\n   · RUN_COMMAND permission not granted, or allow-external-apps is disabled in Termux", "\n   · 未授予 RUN_COMMAND 权限、或 Termux 里 allow-external-apps 被关掉");
        ZH.put("\n   · The phone was busy at the time (a backup / self-check running in the background) — most common, just tap Refresh status and retry", "\n   · 手机当时很忙（后台在跑备份/自检之类）—— 最常见，点「刷新状态」再试即可");
        ZH.put("\n   · The system blocked starting a service from the background (most common on widget taps)", "\n   · 系统拦了「从后台启动服务」（小部件点击最容易遇到）");
        ZH.put("\n   · This is a long task (backups and restarts are slow anyway) — give it more time", "\n   · 这次是长任务（备份/重启本来就慢），可以再等等看");
        ZH.put("   If no dialog appeared: Settings → Apps → DSH Console → Permissions → allow RUN_COMMAND.", "   如果没看到弹窗：设置 → 应用 → DSH 控制台 → 权限 → 允许 RUN_COMMAND。");
        ZH.put("  Bridge:", "  桥：");
        ZH.put("  DSH:", "  DSH：");
        ZH.put("  adb:", "  adb：");
        ZH.put(" (Wi-Fi off, or Wireless debugging not on)", "（Wi-Fi 未连，或无线调试没开）");
        ZH.put(" (the source is pushed, only the release is missing)", "（源码已推上去，只差发版）");
        ZH.put(" completed (exit=", " 已完成（exit=");
        ZH.put(" entries (keeps up to ", " 条（最多保留 ");
        ZH.put(" entries)", " 条）");
        ZH.put(" · ", " · ");
        ZH.put(" · checking for a newer release…", " · 正在检查有没有新版本…");
        ZH.put(" · could not check for updates now (no network?)", " · 现在查不了更新（没网？）");
        ZH.put(" · tap this line to update", " · 点这一行更新");
        ZH.put(" · the release channel is still v", " · 发行版还是 v");
        ZH.put(" · the repo source is v", " · 仓库源码 v");
        ZH.put(" · up to date", " · 已是最新");
        ZH.put(" → the release channel has ", " → 发行版有 ");
        ZH.put("(Does not affect DSH / Bridge / adb — each has its own revoke entry.)", "（不影响 DSH／桥／adb —— 它们各有自己的收回入口。）");
        ZH.put("(no entries yet)\n\n", "（还没有记录）\n\n");
        ZH.put("(no output this time)", "（这次没有输出）");
        ZH.put("(no result bundle received; Termux may not be authorized or allow-external-apps is off)\n", "(没有收到结果 bundle；可能是 Termux 未授权或 allow-external-apps 未开)\n");
        ZH.put("(no technical detail this time)", "（这次没有技术细节）");
        ZH.put("(the page address came back on these lines — it carries the token, so it is not written to the log)", "（页面地址就在这几行里 —— 它带着 token，所以不写进日志）");
        ZH.put(")", "）");
        ZH.put(") — the lamps above and the summary line below are updated", "）—— 上面的灯和下面的摘要已更新");
        ZH.put(", took ", "，用时 ");
        ZH.put(", waiting for Termux to reply…", "，等待 Termux 回传…");
        ZH.put("0_emergency-stop", "0_紧急停止");
        ZH.put("1_start-dsh", "1_启动DSH");
        ZH.put("2_shutdown-dsh", "2_关闭DSH");
        ZH.put("3_backup-dsh", "3_备份DSH");
        ZH.put("4_soft-restart-dsh", "4_软重启DSH");
        ZH.put("5_cleanup-dsh", "5_清理DSH");
        ZH.put("6 digits", "6 位数字");
        ZH.put("6_hard-restart-dsh", "6_硬重启DSH");
        ZH.put("7_reconnect-ai", "7_重连AI通道");
        ZH.put("8_enable-wireless-adb", "8_自动开无线调试");
        ZH.put("About this app", "关于本应用");
        ZH.put("Afterwards the AI can no longer use those 6 digits to pass any identity check for you (the security check when installing an APK, ", "之后 AI 就不能再用那 6 位替你过任何身份验证了（装 APK 时的安全验证、");
        ZH.put("Asked the system to open the page — if it did not appear, tap the row below", "已请求系统打开页面 —— 要是没出现，就点下面那一行");
        ZH.put("Authorize", "授权");
        ZH.put("Authorize the AI to use your password", "授权 AI 使用你的密码");
        ZH.put("Auto refresh status", "自动刷新状态");
        ZH.put("Backup", "备份");
        ZH.put("Bridge", "桥");
        ZH.put("Bridge running", "桥运行中");
        ZH.put("Bridge state", "桥状态");
        ZH.put("Bridge status", "桥状态查询");
        ZH.put("Bridge: just dropped (wakeable)", "桥：刚断（可唤醒）");
        ZH.put("Bridge: long silent", "桥：长时间未响应");
        ZH.put("Bridge: long silent (bound but not answering)", "桥：长时间未响应（端口在听却不应答）");
        ZH.put("Bridge: not installed", "桥：未安装");
        ZH.put("Bridge: running", "桥：运行中");
        ZH.put("Bridge: unknown", "桥：状态查询失败");
        ZH.put("Cancel", "取消");
        ZH.put("Channels (adb and bridge separate)", "通道（adb 与桥分开）");
        ZH.put("Check for updates", "检查更新");
        ZH.put("Cleanup", "清理");
        ZH.put("Clear", "清空");
        ZH.put("Close", "关闭");
        ZH.put("Confirmation required: restart/shutdown drops the current web session, and a full stop of the bridge may need a manual open on this ROM.", "需要确认：重启/关闭会断开当前网页会话；真停桥在这台 ROM 上可能唤不回来，只能手动打开一次。");
        ZH.put("Connect adb", "连接 adb");
        ZH.put("Copy all", "全部复制");
        ZH.put("Copy failed: ", "复制失败：");
        ZH.put("Could not open the page: ", "打不开页面：");
        ZH.put("DSH", "DSH");
        ZH.put("DSH Console", "DSH 控制台");
        ZH.put("DSH Console ", "DSH 控制台 ");
        ZH.put("DSH Console log", "DSH 控制台日志");
        ZH.put("DSH opened the page itself while starting (its boot log says so) — I did not open a second one", "页面是 DSH 启动时自己打开的（它的启动日志里写着），我没有再开第二个");
        ZH.put("Danger zone · only you can undo it by hand", "危险操作 · 只能你手动恢复");
        ZH.put("Deletes only this kit's own artifacts. Your files are not touched.", "只删本工具自己的产物，不碰你的文件。");
        ZH.put("Downloads the two APKs from GitHub Releases, verifies SHA256, then installs them.", "从 GitHub Releases 下载两个 APK，校验 SHA256 后安装。");
        ZH.put("Emergency", "紧急");
        ZH.put("Emergency stop", "紧急停止");
        ZH.put("English", "English");
        ZH.put("Failed to start the Termux command: ", "启动 Termux 命令失败：");
        ZH.put("Four states from one ping plus the state note (no timers): running / just dropped (wakeable, one broadcast brings it back) / long silent (the process went away on its own or is bound but not answering - waking may work, otherwise open DSH Bridge once) / not installed (this install has never been seen alive here).", "四态由**一次 ping 的结果 + 状态记录**判定（不看时间）：运行中 / 刚断（可唤醒，一条广播就能拉回）/ 长时间未响应（进程自己没了，或端口在听却不应答 —— 唤醒可能有效，无效就手动打开一次「DSH 桥」）/ 未安装（这台机器上从没见过它是活的）。");
        ZH.put("Fully stop bridge", "真停桥");
        ZH.put("Get the page address", "获取页面地址");
        ZH.put("Green = listening and answering, grey = soft-stopped or not installed.", "绿=在听且真应答，灰=软停或未安装。");
        ZH.put("Green = the web service answers, yellow = half-started, red = down, grey = not running.", "绿=网页服务正常应答，黄=半启动，红=挂了，灰=没在跑。");
        ZH.put("Green = usable, yellow = connecting, red = failed, grey = not connected (check Wi-Fi).", "绿=可用，黄=连接中，红=失败，灰=未连接（看 Wi-Fi）。");
        ZH.put("Hard restart", "硬重启");
        ZH.put("History: scrollable, copyable. Results you tapped and automatic refreshes are kept apart and never overwrite each other.", "历史记录：可滚动、可复制。你点出来的和自动刷新的分开记，互不覆盖。");
        ZH.put("Installed version and whether a newer release exists. If the check fails it says so instead of claiming it is up to date.", "已装版本 + 有没有新发行版。查不到就直说查不到，不谎报「已是最新」。");
        ZH.put("It takes a couple of minutes and needs your 6-digit password for the system install dialog.", "要一两分钟，装包页需要你交一次那 6 位密码。");
        ZH.put("Language", "语言");
        ZH.put("Lets the App exit and unbinds accessibility. On this vivo it may not be wakeable again - you would have to open DSH Bridge by hand.", "让 App 退出并解绑无障碍。这台 vivo 上可能唤不回来 —— 只能你手动打开「DSH 桥」。");
        ZH.put("Log", "日志");
        ZH.put("Log (", "日志（");
        ZH.put("Log cleared", "日志已清空");
        ZH.put("Log copied (", "日志已复制（");
        ZH.put("Maintenance", "维护");
        ZH.put("Must be 6 digits", "必须是 6 位数字");
        ZH.put("Network first aid", "网络急救");
        ZH.put("No browser to open it with; the address is github.com/Maopk/dsh-termux-kit", "没有可用的浏览器；地址是 github.com/Maopk/dsh-termux-kit");
        ZH.put("No reply the first time, resending: ", "第一次没回音，正在补发：");
        ZH.put("No status yet — tap Refresh status", "还没有状态 —— 点「刷新状态」");
        ZH.put("Now: authorized (the AI can pass system identity checks for you)", "当前：已授权（AI 可代你过系统身份验证）");
        ZH.put("Now: revoked", "当前：已收回");
        ZH.put("Now: unreadable (no reply from Termux; tap Refresh status to retry)", "当前：读不到（Termux 没回话；点「刷新状态」再试）");
        ZH.put("OK", "好");
        ZH.put("On = DSH may drive the phone through this app (listening on 127.0.0.1:8788). Off = soft stop: the port closes, the process stays, and one broadcast brings it back.", "开 = 允许 DSH 通过本 App 操作手机（监听 127.0.0.1:8788）。关 = 软停：端口关闭、进程保留，一条广播就能拉回。");
        ZH.put("On = the AI may use your 6-digit lock-screen password to pass identity checks for you (installing packages, lifting settings restrictions, etc.); Off = revoked at once", "开 = AI 可用你的 6 位锁屏密码替你过系统身份验证（装包、解除设置限制等）；关 = 立刻收回");
        ZH.put("On = the AI may use your 6-digit lock-screen password to pass system verification for you (installing packages, removing settings restrictions). Off = revoked at once. It is never used to unlock the phone and read content, to pay, or for anything unrelated to the task at hand.", "开 = AI 可动用你的 6 位密码替你过系统验证（装包、解除应用设置限制）；关 = 立刻收回。绝不用于解锁手机翻看内容、支付/免密、或与当次任务无关的场景。");
        ZH.put("Open UI", "打开界面");
        ZH.put("Opens github.com/Maopk/dsh-termux-kit - source, releases and docs.", "打开 github.com/Maopk/dsh-termux-kit —— 源码、发行版和文档。");
        ZH.put("Packs DSH state and verifies the archive; the result goes to Download/dsh/.", "打包 DSH 状态并校验归档；产物落 Download/dsh/。");
        ZH.put("Password access", "密码使用权");
        ZH.put("Password access: ", "密码使用权：");
        ZH.put("Project page", "项目主页");
        ZH.put("Project page: ", "项目地址：");
        ZH.put("Query password access", "查询密码使用权");
        ZH.put("Read-only: is the port listening, does it really answer, version, paused flag.", "只读：端口是否在听、是否真应答、版本、是否被暂停。");
        ZH.put("Reading authorization state…", "正在读取授权状态…");
        ZH.put("Reading status…", "正在读取状态…");
        ZH.put("Reads the state once and updates the lamps. Read-only: it never wakes a channel.", "只读读一次状态并更新状态灯，**不会唤醒任何通道**。");
        ZH.put("Refresh status", "刷新状态");
        ZH.put("Repair adb channel", "修复 adb 通道");
        ZH.put("Restarts after a kill -9 and clears the orphan lock. Cost: drops the current web session.", "强杀后重启并清孤儿锁。代价：会断开当前网页会话。");
        ZH.put("Restarts the service with SIGTERM. Cost: drops the current web session.", "用 SIGTERM 重启服务。代价：会断开当前网页会话。");
        ZH.put("Restore both channels", "恢复全部通道");
        ZH.put("Revoke", "收回");
        ZH.put("Revoke password access", "收回密码使用权");
        ZH.put("Revoke password access?", "收回密码使用权？");
        ZH.put("Revokes the AI's control of the phone: soft-stops the bridge and revokes the token. adb is a separate channel and stays up.", "撤销 AI 对手机的控制：软停桥 + 吊销 token。adb 是另一条通道，不受影响。");
        ZH.put("Revoking…", "正在收回……");
        ZH.put("Run", "执行");
        ZH.put("Run ", "运行 ");
        ZH.put("Running: ", "正在执行：");
        ZH.put("Runs the whole self-test suite in Termux (70 checks: syntax, dry-runs, regression, real runs, a cold-start sandbox); the last line is the verdict. It takes minutes and loads the phone — pick a quiet moment. Script: ~/dsh-termux-kit/tests/selftest.sh", "在 Termux 里跑完整自检套件（70 项：语法、预演、回归、真跑、冷启动沙箱），最后一行就是结论。要几分钟且会压负载，挑空闲时跑。脚本路径：~/dsh-termux-kit/tests/selftest.sh");
        ZH.put("Security", "安全");
        ZH.put("Self-check", "自检");
        ZH.put("Sends one token-carrying broadcast. Never takes your screen. Can take 20-40s if the process was reclaimed.", "发一条带 token 的广播把它唤回，绝不抢你的屏幕。进程被回收时要 20-40 秒。");
        ZH.put("Sent: ", "已发送：");
        ZH.put("Sent: Wake bridge", "已发送：唤醒桥");
        ZH.put("Sent: stop the bridge listening", "已发送：让桥停止监听");
        ZH.put("Settings", "设置");
        ZH.put("Soft restart", "软重启");
        ZH.put("Start / Stop", "启动 / 停止");
        ZH.put("Start DSH", "启动 DSH");
        ZH.put("Starts DSH and opens the page; if it is already running it only opens the page.", "启动 DSH 并打开页面；已在运行则只打开页面。");
        ZH.put("Status / Log", "状态 / 日志");
        ZH.put("Status parse failed (callback may be truncated): ", "状态解析失败（回传可能被截断）：");
        ZH.put("Status parse failed: ", "状态解析失败：");
        ZH.put("Stop DSH", "关闭 DSH");
        ZH.put("Stops DSH and closes the browser. The bridge is a separate channel and is left alone by default.", "关闭 DSH 并关浏览器。桥是另一条通道，默认不动它。");
        ZH.put("System", "跟随系统");
        ZH.put("System / Chinese / English. The widgets and the page panel follow this too.", "跟随系统 / 中文 / English。小组件和页面面板也跟着变。");
        ZH.put("Tap Refresh to read status", "点「刷新」读取状态");
        ZH.put("Task", "任务");
        ZH.put("Technical detail (kept out of the subtitle on purpose):", "技术细节（故意不放在副标题里）：");
        ZH.put("The startup script asked Termux to open the page — if it did not appear, tap the row below", "启动脚本已经让 Termux 去开页面了 —— 要是没出现，就点下面那一行");
        ZH.put("This device has no clipboard service", "本机没有剪贴板服务");
        ZH.put("This revokes it: ~/.dsh-auth-pass is deleted.\n", "收回后：~/.dsh-auth-pass 会被删除。\n");
        ZH.put("Turn the switch off at any time to revoke.", "随时把开关关掉即可收回。");
        ZH.put("Type that 6-digit lock-screen password → it is written to ~/.dsh-auth-pass (600).\n", "输入那 6 位锁屏密码 → 写进 ~/.dsh-auth-pass（600）。\n");
        ZH.put("Unknown control: ", "表里没有这个控件：");
        ZH.put("Update", "更新");
        ZH.put("Update the two apps", "更新两个 App");
        ZH.put("Used only to pass system identity checks for you (installing packages, lifting settings restrictions, etc.).\n", "用途仅限：替你过系统身份验证（装包、解除设置限制等）。\n");
        ZH.put("Version", "版本");
        ZH.put("Version: ", "版本：");
        ZH.put("Wake bridge", "唤醒桥");
        ZH.put("When foreign sites die: decides whether the Clash core stopped or the config went bad, then repairs.", "外网全挂时用：先判 Clash 核心停了还是配置坏了，再修。");
        ZH.put("Wi-Fi state → Wireless debugging switch (written through the bridge) → port → connect → verify. Says which step failed.", "Wi-Fi 状态 → 无线调试开关（这一步借桥来写）→ 端口 → 连接 → 复核。卡在哪一步就说哪一步。");
        ZH.put("Wireless debugging only. Needs a real Wi-Fi network, not just the switch.", "只走无线调试。需要有真实可用的 Wi-Fi，不只是拨开关。");
        ZH.put("Write password authorization", "写入密码授权");
        ZH.put("Writing authorization…", "正在写入授权……");
        ZH.put("] exit=", "] 退出码=");
        ZH.put("adb", "adb");
        ZH.put("adb first, then the bridge. Use only when you need both; a failure names the channel it came from.", "先 adb 后桥。两条都要时才用；失败会说清是哪条通道。");
        ZH.put("adb · wireless debugging, needs working Wi-Fi", "adb · 无线调试，需要可用 Wi-Fi");
        ZH.put("auto follows the system language", "自动跟随系统语言");
        ZH.put("bridge · accessibility loopback, no network", "桥 · 无障碍回环，不需要网络");
        ZH.put("half-started (the port is listening, the page does not answer yet)", "半启动（端口在听，页面还没应答）");
        ZH.put("lifting app settings restrictions, sensitive confirmations in developer options… they all stop with you).\n", "解除应用设置限制、开发者选项里的敏感确认……都回到你自己手上）。\n");
        ZH.put("none", "无");
        ZH.put("not connected", "未连接");
        ZH.put("running", "运行中");
        ZH.put("s (this one usually answers within ", " 秒（这条通常 ");
        ZH.put("s (usually ≤", "s（通常 ≤");
        ZH.put("s)", "s）");
        ZH.put("s). Likely causes, most common first:", " 秒内回来）。最可能的原因，按概率排序：");
        ZH.put("stopped", "已停止");
        ZH.put("the widgets and the page panel follow this too", "小组件和页面面板也跟着变");
        ZH.put("· Empty output still gets a (no output this time) line, so nothing is left blank\n", "· 输出为空也会写明「这次没有输出」，不会留白\n");
        ZH.put("· Tap Refresh status to read the three lamps\n", "· 点「刷新状态」读三个灯\n");
        ZH.put("· Tap any task button to run it: sent, callback, exit code and raw output are all recorded here\n", "· 点任意任务按钮执行：发送、回传、退出码、原始输出都记在这里\n");
        ZH.put("⏳ Running: ", "⏳ 正在执行：");
        ZH.put("▶ Open the DSH page", "▶ 打开 DSH 页面");
        ZH.put("● Bridge", "● 桥");
        ZH.put("● DSH", "● DSH");
        ZH.put("● adb", "● adb");
        ZH.put("⚠ Failed to start the Termux command.", "⚠ 启动 Termux 命令失败。");
        ZH.put("⚠ I have the page address but have not verified it this time — tap the row below if you want to open it", "⚠ 页面地址拿到了，但这次没验证它还灵不灵 —— 想打开就点下面那一行");
        ZH.put("⚠ No callback from Termux after ", "⚠ 等了 ");
        ZH.put("⚠ RUN_COMMAND permission not granted yet; a permission prompt was shown.\n", "⚠ 还没拿到 RUN_COMMAND 权限；已弹出授权提示。\n");
        ZH.put("⚠ Termux (com.termux) not found; please install Termux first.", "⚠ 找不到 Termux（com.termux）；请先安装 Termux。");
        ZH.put("　(tap here for the log)", "　（点这里看日志）");
        ZH.put("　waited ", "　已等待 ");
        ZH.put("　waited 0s", "　已等待 0s");
        ZH.put("　⚠ missing RUN_COMMAND permission", "　⚠ 缺少 RUN_COMMAND 权限");
        // <<< generated by tools/i18n-table <<<
    }

    private Lang() {}

    static String systemLang() {
        String l = Locale.getDefault().getLanguage();
        return l == null ? "en" : l;
    }

    static String readMode() {
        try {
            File f = new File(LANG_FILE);
            if (f.canRead()) {
                BufferedReader r = new BufferedReader(new FileReader(f));
                String v = r.readLine();
                r.close();
                if (v != null) {
                    v = v.trim();
                    if (v.equals("zh") || v.equals("en") || v.equals("auto")) return v;
                }
            }
        } catch (Throwable ignored) {}
        return mode;
    }

    /** The app cannot read ~/.dsh-lang (it lives in Termux's private directory), so its own choice
     *  is persisted in SharedPreferences; ~/.dsh-lang is written for the scripts through Termux. */
    static void init(android.content.Context c) {
        try {
            String saved = c.getSharedPreferences("dsh-console", android.content.Context.MODE_PRIVATE)
                    .getString("lang", null);
            if (saved != null) mode = saved;
            else mode = readMode();          // fall back to the file when it happens to be readable
        } catch (Throwable t) { /* keep the current mode */ }
        cur = mode.equals("auto") ? (systemLang().startsWith("zh") ? "zh" : "en") : mode;
    }

    static String mode() { return mode; }
    static boolean isZh() { return cur.equals("zh"); }

    static void setMode(android.content.Context c, String v) {
        if (v.equals("zh") || v.equals("en") || v.equals("auto")) {
            mode = v;
            cur = v.equals("auto") ? (systemLang().startsWith("zh") ? "zh" : "en") : v;
            try {
                c.getSharedPreferences("dsh-console", android.content.Context.MODE_PRIVATE)
                        .edit().putString("lang", v).apply();
            } catch (Throwable t) { /* not fatal: only the persistence is lost */ }
        }
    }

    static String t(String en) {
        if (!cur.equals("zh") || en == null) return en;
        String z = ZH.get(en);
        return z == null ? en : z;
    }
}
