package io.dsh.console;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Tiny built-in two-language table (named Lang, not L: MainActivity has a local JSONObject called L).
 *
 * Why not the Android way: this app is built with plain javac + android.jar, so there is no
 * AndroidX and therefore no AppCompatDelegate.setApplicationLocales(). A small table plus a
 * preference (and recreate()) gives the same result with zero dependencies.
 *
 * The switch writes the SAME file the shell scripts read - ~/.dsh-lang - so the app, the DSH page
 * panel and the 10 widgets never disagree about the current language. That file lives in Termux's
 * private directory, which this app cannot touch directly, so it is written by running
 * "dsh-lang set <v>" through the RUN_COMMAND channel instead.
 *
 * A key that is missing returns the English string unchanged, so a gap shows one English line
 * rather than an empty label.
 */
final class Lang {
    static final String LANG_FILE = "/data/data/com.termux/files/home/.dsh-lang";
    static final String[] MODES = {"auto", "zh", "en"};
    private static final Map<String, String> ZH = new HashMap<>();
    private static String mode = "auto";
    private static String cur = "en";

    static {
        // >>> generated by tools/i18n-table — do not edit by hand >>>
        ZH.put("\n\n⚠ Confirmation required: restart/shutdown drops the current web session; ", "\n\n⚠ 需要二次确认：重启/关闭会断开当前网页会话；");
        ZH.put("\n   · RUN_COMMAND permission not granted, or allow-external-apps is disabled in Termux", "\n   · 未授予 RUN_COMMAND 权限、或 Termux 里 allow-external-apps 被关掉");
        ZH.put("\n   · The phone was busy at the time (a backup / self-check running in the background) — most common, just tap Refresh status and retry", "\n   · 手机当时很忙（后台在跑备份/自检之类）—— 最常见，点「刷新状态」再试即可");
        ZH.put("\n   · The system blocked starting a service from the background (most common on widget taps)", "\n   · 系统拦了「从后台启动服务」（小部件点击最容易遇到）");
        ZH.put("\n   · This is a long task (backups and restarts are slow anyway) — give it more time", "\n   · 这次是长任务（备份/重启本来就慢），可以再等等看");
        ZH.put("   If no dialog appeared: Settings → Apps → DSH Console → Permissions → allow RUN_COMMAND.", "   如果没看到弹窗：设置 → 应用 → DSH 控制台 → 权限 → 允许 RUN_COMMAND。");
        ZH.put("  Bridge:", "  桥：");
        ZH.put("  DSH:", "  DSH：");
        ZH.put("  adb:", "  adb：");
        ZH.put(" completed (exit=", " 已完成（exit=");
        ZH.put(" entries (keeps up to ", " 条（最多保留 ");
        ZH.put(" entries)", " 条）");
        ZH.put(" · ", " · ");
        ZH.put("(Does not affect DSH / Bridge / adb — each has its own revoke entry.)", "（不影响 DSH／桥／adb —— 它们各有自己的收回入口。）");
        ZH.put("(no entries yet)\n\n", "（还没有记录）\n\n");
        ZH.put("(no output this time)", "（这次没有输出）");
        ZH.put("(no result bundle received; Termux may not be authorized or allow-external-apps is off)\n", "(没有收到结果 bundle；可能是 Termux 未授权或 allow-external-apps 未开)\n");
        ZH.put(")", "）");
        ZH.put(") — the lamps above and the summary line below are updated", "）—— 上面的灯和下面的摘要已更新");
        ZH.put(", took ", "，用时 ");
        ZH.put(", waiting for Termux to reply…", "，等待 Termux 回传…");
        ZH.put("0_emergency-stop", "0_紧急停止");
        ZH.put("1_start-dsh", "1_启动DSH");
        ZH.put("2_shutdown-dsh", "2_关闭DSH");
        ZH.put("3_backup-dsh", "3_备份DSH");
        ZH.put("4_soft-restart-dsh", "4_软重启DSH");
        ZH.put("5_cleanup-dsh", "5_清理DSH");
        ZH.put("6 digits", "6 位数字");
        ZH.put("6_hard-restart-dsh", "6_硬重启DSH");
        ZH.put("7_reconnect-ai", "7_重连AI通道");
        ZH.put("8_enable-wireless-adb", "8_自动开无线调试");
        ZH.put("Accessibility loopback only: a broadcast carrying the token, no network needed", "只走无障碍回环：带 token 的广播，不需要网络");
        ZH.put("Afterwards the AI can no longer use those 6 digits to pass any identity check for you (the security check when installing an APK, ", "之后 AI 就不能再用那 6 位替你过任何身份验证了（装 APK 时的安全验证、");
        ZH.put("Authorize", "授权");
        ZH.put("Authorize the AI to use your password", "授权 AI 使用你的密码");
        ZH.put("Auto refresh status", "自动刷新状态");
        ZH.put("Backup", "备份");
        ZH.put("Bridge", "桥");
        ZH.put("Bridge only: port / whether it really answers / version / paused", "只查桥：端口 / 是否真应答 / 版本 / paused");
        ZH.put("Cancel", "取消");
        ZH.put("Channels (adb and bridge separate)", "通道（adb 与桥分开）");
        ZH.put("Check bridge status", "查看桥状态");
        ZH.put("Chinese", "中文");
        ZH.put("Cleanup", "清理");
        ZH.put("Clear", "清空");
        ZH.put("Close", "关闭");
        ZH.put("Commands run through Termux (RUN_COMMAND channel); this app has no storage, network, or accessibility permission.\n", "命令经 Termux 执行（RUN_COMMAND 通道）；本 App 无存储/网络/无障碍权限。\n");
        ZH.put("Connect adb", "连 adb");
        ZH.put("Copy all", "全部复制");
        ZH.put("Copy failed: ", "复制失败：");
        ZH.put("DSH Console", "DSH 控制台");
        ZH.put("DSH Console ", "DSH 控制台 ");
        ZH.put("DSH Console log", "DSH 控制台日志");
        ZH.put("Decides whether the Clash core is stopped or the generated config went bad, then repairs it (clash-doctor --fix)", "判断是 Clash 核心被停了、还是生成的配置坏了，然后修好它（clash-doctor --fix）");
        ZH.put("Deletes only my own artifacts; never touches config or notes", "只删我自己的产物；绝不碰配置与笔记");
        ZH.put("Emergency", "紧急");
        ZH.put("Emergency stop", "紧急停止");
        ZH.put("English", "English");
        ZH.put("Every run is recorded in the log: sent, callback, exit code, raw output.", "每次执行都记在「日志」里：发送、回传、退出码、原始输出。");
        ZH.put("Failed to start the Termux command: ", "启动 Termux 命令失败：");
        ZH.put("For when you need both channels: adb first, then the bridge; a failure names the channel it came from", "两条通道都要时用：先 adb，再桥；哪条失败会说哪条");
        ZH.put("Hard restart", "硬重启");
        ZH.put("Language", "语言");
        ZH.put("Log", "日志");
        ZH.put("Log (", "日志（");
        ZH.put("Log cleared", "日志已清空");
        ZH.put("Log copied (", "日志已复制（");
        ZH.put("Maintenance", "维护");
        ZH.put("Must be 6 digits", "必须是 6 位数字");
        ZH.put("Network first aid", "网络急救");
        ZH.put("No reply the first time, resending: ", "第一次没回音，正在补发：");
        ZH.put("No status yet — tap Refresh status", "还没有状态 —— 点「刷新状态」");
        ZH.put("Now: authorized (the AI can pass identity checks for you)", "当前：已授权（AI 可代你过身份验证）");
        ZH.put("Now: not authorized (any password-protected check needs you in person)", "当前：未授权（任何需要密码的验证都要你本人）");
        ZH.put("On = the AI may use your 6-digit lock-screen password to pass identity checks for you (installing packages, lifting settings restrictions, etc.); Off = revoked at once", "开 = AI 可用你的 6 位锁屏密码替你过系统身份验证（装包、解除设置限制等）；关 = 立刻收回");
        ZH.put("Open UI", "打开界面");
        ZH.put("Open Web UI", "打开 Web UI");
        ZH.put("Opening log", "正在打开日志");
        ZH.put("Opens the page at the address in ~/.dsh-url (prefers the desktop PWA)", "用 ~/.dsh-url 里的地址开页面（优先桌面 PWA）");
        ZH.put("Opens the page directly if it is already running; includes the start mutex and a real readiness check", "已在跑则直接开页面；含启动互斥与真就绪判定");
        ZH.put("Packs and verifies the archive (zstd -t + entry count)", "打包并校验归档（zstd -t + 条目数）");
        ZH.put("Password access", "密码使用权");
        ZH.put("Query password access", "查询密码使用权");
        ZH.put("Reading authorization state…", "正在读取授权状态…");
        ZH.put("Reading status…", "正在读取状态…");
        ZH.put("Refresh status", "刷新状态");
        ZH.put("Restarts after SIGTERM; drops the current web session", "SIGTERM 后重启，会断开当前网页会话");
        ZH.put("Restarts after a -9 kill; drops the current web session", "-9 强杀后重启，会断开当前网页会话");
        ZH.put("Restore everything (adb + bridge)", "全部恢复（adb + 桥）");
        ZH.put("Revoke", "收回");
        ZH.put("Revoke password access", "收回密码使用权");
        ZH.put("Revoke password access?", "收回密码使用权？");
        ZH.put("Revokes the AI's control of the phone (bridge stop + revoke token)", "撤销 AI 对手机的控制（桥 stop + 吊销 token）");
        ZH.put("Revoking…", "正在收回……");
        ZH.put("Run", "执行");
        ZH.put("Run ", "执行 ");
        ZH.put("Running: ", "正在执行：");
        ZH.put("Sent: ", "已发送：");
        ZH.put("Shut down DSH", "关闭 DSH");
        ZH.put("Soft restart", "软重启");
        ZH.put("Start / Stop", "启动 / 停止");
        ZH.put("Start DSH", "启动 DSH");
        ZH.put("State: unreadable (no callback from Termux; tap Refresh status to retry)", "状态：读不到（Termux 没回传；点「刷新状态」重试）");
        ZH.put("Status parse failed (callback may be truncated): ", "状态解析失败（回传可能被截断）：");
        ZH.put("Status parse failed: ", "状态解析失败：");
        ZH.put("Stops DSH and closes the browser; the bridge is a separate channel and is left alone by default", "停 DSH 并关掉 DSH 窗口；桥是独立通道，默认不动它");
        ZH.put("System", "跟随系统");
        ZH.put("Tap Refresh to read status", "点「刷新」读取状态");
        ZH.put("Task", "任务");
        ZH.put("This device has no clipboard service", "本机没有剪贴板服务");
        ZH.put("This revokes it: ~/.dsh-auth-pass is deleted.\n", "收回后：~/.dsh-auth-pass 会被删除。\n");
        ZH.put("Turn the switch off at any time to revoke.", "随时把开关关掉即可收回。");
        ZH.put("Type that 6-digit lock-screen password → it is written to ~/.dsh-auth-pass (600).\n", "输入那 6 位锁屏密码 → 写进 ~/.dsh-auth-pass（600）。\n");
        ZH.put("Used only to pass system identity checks for you (installing packages, lifting settings restrictions, etc.).\n", "用途仅限：替你过系统身份验证（装包、解除设置限制等）。\n");
        ZH.put("Wake bridge", "唤醒桥");
        ZH.put("Wireless debugging only: set the switch → find the port → adb connect (needs working Wi-Fi)", "只走无线调试：置开关 → 找端口 → adb connect（需要可用 Wi-Fi）");
        ZH.put("Write password authorization", "写入密码授权");
        ZH.put("Writing authorization…", "正在写入授权……");
        ZH.put("] exit=", "] 退出码=");
        ZH.put("auto follows the system language", "auto 跟随系统语言");
        ZH.put("just now", "刚刚");
        ZH.put("lifting app settings restrictions, sensitive confirmations in developer options… they all stop with you).\n", "解除应用设置限制、开发者选项里的敏感确认……都回到你自己手上）。\n");
        ZH.put("none", "无");
        ZH.put("not connected", "未连接");
        ZH.put("port open but not answering", "端口开着但不应答");
        ZH.put("port open but not ready", "端口开着但没就绪");
        ZH.put("revoke-style actions do not come back on their own (re-authorize to restore).", "撤销类动作不会自己恢复（要恢复需重新授权）。");
        ZH.put("running", "在跑");
        ZH.put("running (HTTP ", "运行中（HTTP ");
        ZH.put("s (this one usually answers within ", " 秒（这条通常 ");
        ZH.put("s (usually ≤", "s（通常 ≤");
        ZH.put("s ago", " 秒前");
        ZH.put("s)", "s）");
        ZH.put("s). Likely causes, most common first:", " 秒内回来）。最可能的原因，按概率排序：");
        ZH.put("stopped", "停了");
        ZH.put("the widgets and the page panel follow this too", "组件与页面面板也跟随这个设置");
        ZH.put("· Empty output still gets a (no output this time) line, so nothing is left blank\n", "· 输出为空也会写明「这次没有输出」，不会留白\n");
        ZH.put("· Tap Refresh status to read the three lamps\n", "· 点「刷新状态」读三个灯\n");
        ZH.put("· Tap any task button to run it: sent, callback, exit code and raw output are all recorded here\n", "· 点任意任务按钮执行：发送、回传、退出码、原始输出都记在这里\n");
        ZH.put("⏳ Running: ", "⏳ 正在执行：");
        ZH.put("● Bridge", "● 桥");
        ZH.put("● DSH", "● DSH");
        ZH.put("● DSH　● Bridge　● adb", "● DSH　● 桥　● adb");
        ZH.put("● adb", "● adb");
        ZH.put("⚠ Failed to start the Termux command.", "⚠ 启动 Termux 命令失败。");
        ZH.put("⚠ No callback from Termux after ", "⚠ 等了 ");
        ZH.put("⚠ RUN_COMMAND permission not granted yet; a permission prompt was shown.\n", "⚠ 还没拿到 RUN_COMMAND 权限；已弹出授权提示。\n");
        ZH.put("⚠ Termux (com.termux) not found; please install Termux first.", "⚠ 找不到 Termux（com.termux）；请先安装 Termux。");
        ZH.put("　(tap here for the log)", "　（点这里看日志）");
        ZH.put("　Bridge ", "　桥 ");
        ZH.put("　DSH ", "　DSH ");
        ZH.put("　adb ", "　adb ");
        ZH.put("　waited ", "　已等待 ");
        ZH.put("　waited 0s", "　已等待 0s");
        ZH.put("　⚠ missing RUN_COMMAND permission", "　⚠ 缺少 RUN_COMMAND 权限");
        // <<< generated by tools/i18n-table <<<
    }

    private Lang() {}

    static String systemLang() {
        String l = Locale.getDefault().getLanguage();
        return l == null ? "en" : l;
    }

    static String readMode() {
        try {
            File f = new File(LANG_FILE);
            if (f.canRead()) {
                BufferedReader r = new BufferedReader(new FileReader(f));
                String v = r.readLine();
                r.close();
                if (v != null) {
                    v = v.trim();
                    if (v.equals("zh") || v.equals("en") || v.equals("auto")) return v;
                }
            }
        } catch (Throwable ignored) {}
        return mode;
    }

    /** The app cannot read ~/.dsh-lang (it lives in Termux's private directory), so its own choice
     *  is persisted in SharedPreferences; ~/.dsh-lang is written for the scripts through Termux. */
    static void init(android.content.Context c) {
        try {
            String saved = c.getSharedPreferences("dsh-console", android.content.Context.MODE_PRIVATE)
                    .getString("lang", null);
            if (saved != null) mode = saved;
            else mode = readMode();          // fall back to the file when it happens to be readable
        } catch (Throwable t) { /* keep the current mode */ }
        cur = mode.equals("auto") ? (systemLang().startsWith("zh") ? "zh" : "en") : mode;
    }

    static String mode() { return mode; }
    static boolean isZh() { return cur.equals("zh"); }

    static void setMode(android.content.Context c, String v) {
        if (v.equals("zh") || v.equals("en") || v.equals("auto")) {
            mode = v;
            cur = v.equals("auto") ? (systemLang().startsWith("zh") ? "zh" : "en") : v;
            try {
                c.getSharedPreferences("dsh-console", android.content.Context.MODE_PRIVATE)
                        .edit().putString("lang", v).apply();
            } catch (Throwable t) { /* not fatal: only the persistence is lost */ }
        }
    }

    static String t(String en) {
        if (!cur.equals("zh") || en == null) return en;
        String z = ZH.get(en);
        return z == null ? en : z;
    }
}
